* added new test script for new threading system * added new target 'testthreads' to Makefile * added two test cases that test variations of thread stopping

diff --git a/test/Makefile.in b/test/Makefile.in
--- a/test/Makefile.in
+++ b/test/Makefile.in
@@ -23,6 +23,19 @@ test:
 			exit 1 ;\
 		fi
 
+testthreads:
+		@echo "*** Running tests for new threading system"
+		@DESTDIR=`pwd` ; export DESTDIR ;\
+		. ../ENVIRONMENT ;\
+		cd $(srcdir)/regression &&\
+		if ./TestScriptThread ; then \
+			echo "*** Passed" ; \
+			exit 0 ;\
+		else \
+			echo "*** Failed" ; \
+			exit 1 ;\
+		fi
+
 clean:
 		rm -f *.class kaffe.core core
 
