* configure.in (KAFFEH_FOR_BUILD): better tell the user how to set it up if it is not found, by setting the KAFFEH environment variable... * configure: regen

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6657,15 +6657,15 @@ if test "$cross_compiling" = yes; then
 set dummy kaffeh; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
 echo "configure:6660: checking for $ac_word" >&5
-if eval "test \"`echo '$''{'ac_cv_path_KAFFEH_FOR_BUILD'+set}'`\" = set"; then
+if eval "test \"`echo '$''{'ac_cv_path_KAFFEH'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
-  case "$KAFFEH_FOR_BUILD" in
+  case "$KAFFEH" in
   /*)
-  ac_cv_path_KAFFEH_FOR_BUILD="$KAFFEH_FOR_BUILD" # Let the user override the test with a path.
+  ac_cv_path_KAFFEH="$KAFFEH" # Let the user override the test with a path.
   ;;
   ?:/*)			 
-  ac_cv_path_KAFFEH_FOR_BUILD="$KAFFEH_FOR_BUILD" # Let the user override the test with a dos path.
+  ac_cv_path_KAFFEH="$KAFFEH" # Let the user override the test with a dos path.
   ;;
   *)
   IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
@@ -6673,7 +6673,7 @@ else
   for ac_dir in $ac_dummy; do 
     test -z "$ac_dir" && ac_dir=.
     if test -f $ac_dir/$ac_word; then
-      ac_cv_path_KAFFEH_FOR_BUILD="$ac_dir/$ac_word"
+      ac_cv_path_KAFFEH="$ac_dir/$ac_word"
       break
     fi
   done
@@ -6681,16 +6681,17 @@ else
   ;;
 esac
 fi
-KAFFEH_FOR_BUILD="$ac_cv_path_KAFFEH_FOR_BUILD"
-if test -n "$KAFFEH_FOR_BUILD"; then
-  echo "$ac_t""$KAFFEH_FOR_BUILD" 1>&6
+KAFFEH="$ac_cv_path_KAFFEH"
+if test -n "$KAFFEH"; then
+  echo "$ac_t""$KAFFEH" 1>&6
 else
   echo "$ac_t""no" 1>&6
 fi
 
-  if test -n "${KAFFEH_FOR_BUILD}"; then
-    { echo "configure: error: cross builds require a locally-executable pre-installed kaffeh" 1>&2; exit 1; }
+  if test -z "${KAFFEH}"; then
+    { echo "configure: error: please set KAFFEH to the full pathname of a locally executable kaffeh" 1>&2; exit 1; }
   fi
+  KAFFEH_FOR_BUILD="$KAFFEH"
   MAKE_KAFFEH_FOR_BUILD=":"
 else
   KAFFEH_FOR_BUILD="\$(top_builddir)/kaffe/kaffeh/kaffeh\$(EXEEXT)"
@@ -6718,7 +6719,7 @@ EOF
 
 
 echo $ac_n "checking how to run the C preprocessor""... $ac_c" 1>&6
-echo "configure:6722: checking how to run the C preprocessor" >&5
+echo "configure:6723: checking how to run the C preprocessor" >&5
 # On Suns, sometimes $CPP names a directory.
 if test -n "$CPP" && test -d "$CPP"; then
   CPP=
@@ -6733,13 +6734,13 @@ else
   # On the NeXT, cc -E runs the code through the compiler's parser,
   # not just through cpp.
   cat > conftest.$ac_ext <<EOF
-#line 6737 "configure"
+#line 6738 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:6743: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:6744: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -6750,13 +6751,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -E -traditional-cpp"
   cat > conftest.$ac_ext <<EOF
-#line 6754 "configure"
+#line 6755 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:6760: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:6761: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -6767,13 +6768,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -nologo -E"
   cat > conftest.$ac_ext <<EOF
-#line 6771 "configure"
+#line 6772 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:6777: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:6778: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -6799,7 +6800,7 @@ echo "$ac_t""$CPP" 1>&6
 
 
 echo $ac_n "checking for path separator""... $ac_c" 1>&6
-echo "configure:6803: checking for path separator" >&5
+echo "configure:6804: checking for path separator" >&5
 if eval "test \"`echo '$''{'ac_cv_kaffe_pathsep'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -6816,7 +6817,7 @@ PATHSEP=$ac_cv_kaffe_pathsep
 
 
 echo $ac_n "checking for directory separator""... $ac_c" 1>&6
-echo "configure:6820: checking for directory separator" >&5
+echo "configure:6821: checking for directory separator" >&5
 if eval "test \"`echo '$''{'ac_cv_kaffe_dirsep'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -7100,6 +7101,7 @@ s%@AWT_DIR@%$AWT_DIR%g
 s%@DLOPEN_JAVA_LIBS@%$DLOPEN_JAVA_LIBS%g
 s%@KLIBFLAGS@%$KLIBFLAGS%g
 s%@KVMLIBFLAGS@%$KVMLIBFLAGS%g
+s%@KAFFEH@%$KAFFEH%g
 s%@KAFFEH_FOR_BUILD@%$KAFFEH_FOR_BUILD%g
 s%@MAKE_KAFFEH_FOR_BUILD@%$MAKE_KAFFEH_FOR_BUILD%g
 s%@nativedir@%$nativedir%g
