Don't require jikes for build with prebuilt rt.jar
2005-01-30  Dalibor Topic  <robilad@kaffe.org>

        * configure.ac: Turn jikes error messages into warnings
        about building tests if kaffe is configured to use
        a precompiled rt.jar.

        Reported by:  Riccardo Mottola <zuse@libero.it>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -491,7 +491,7 @@ ac_includes_default="\
 
 ac_subdirs_all="$ac_subdirs_all kaffe/kaffevm/boehm-gc/boehm"
 ac_subdirs_all="$ac_subdirs_all libltdl"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT abssrcdir CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS LIBLTDL CCLD MKINSTALLDIRS USE_NLS MSGFMT GMSGFMT XGETTEXT MSGMERGE LIBICONV LTLIBICONV INTLLIBS LIBINTL LTLIBINTL POSUB MAY_RUN_PO_TRUE MAY_RUN_PO_FALSE REGEN_FORWARD CONFIG_MD_H CONFIG_CALLKAFFEEXCEPTION_H KAFFEVM_MD_C CONFIG_JIT_MD_H KAFFEVM_JIT_DEF KAFFEVM_ICODE_H HAVE_CONFIG_JIT_MD_H USE_JIT_TRUE USE_JIT_FALSE ENGINE_NAME BCEL_JAR HAVE_BCEL_TRUE HAVE_BCEL_FALSE ENABLE_JVMPI_TRUE ENABLE_JVMPI_FALSE ENABLE_XPROF_TRUE ENABLE_XPROF_FALSE CONFIG_XPROFILE_MD_H JAVAC_FLAGS NEED_LIBXPROF_TRUE NEED_LIBXPROF_FALSE CFLAGS_PG SUN_COMPAT_TRUE SUN_COMPAT_FALSE THREAD_DIR acx_pthread_config PTHREAD_CC PTHREAD_LIBS PTHREAD_CFLAGS SEMAPHORE_LIB VM_LIBS JIKESPROG JIKES KAFFEVM_TRAMPOLINES_C JAVA_LIBS with_engine THREAD_SYSTEM KPREFIX KAFFE_ARCHOS ZIP MKTEMP JASMIN HAVE_ZIP_TRUE HAVE_ZIP_FALSE HAVE_JIKES_TRUE HAVE_JIKES_FALSE HAVE_MKTEMP_TRUE HAVE_MKTEMP_FALSE HAVE_JASMIN_TRUE HAVE_JASMIN_FALSE KAFFE_LIBS M_LIBS NET_LIBS ZIP_LIBS LIBADD_GMP USE_GMP SECURITY_LIBS GC_NAME subdirs BOEHMGC_SPECIFIC_FLAGS HAVE_GCJ_SUPPORT_TRUE HAVE_GCJ_SUPPORT_FALSE LIBOBJS USE_COMPAT_IFADDRS_TRUE USE_COMPAT_IFADDRS_FALSE GTK_CAIRO_TRUE GTK_CAIRO_FALSE COND_NATIVE_AWT_TRUE COND_NATIVE_AWT_FALSE COND_KAFFE_X_AWT_TRUE COND_KAFFE_X_AWT_FALSE X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS AWT_LIBS COND_KAFFE_QT_AWT_TRUE COND_KAFFE_QT_AWT_FALSE MOC UIC QEMBED QT_CXXFLAGS QT_LDADD QT_GUILINK QASSISTANTCLIENT_LDADD COND_CLASSPATH_GTK_AWT_TRUE COND_CLASSPATH_GTK_AWT_FALSE PKG_CONFIG GTK_CFLAGS GTK_LIBS CAIRO_CFLAGS CAIRO_LIBS PANGOFT2_CFLAGS PANGOFT2_LIBS ALSA_CFLAGS ALSA_LIBS ESD_CONFIG ESD_CFLAGS ESD_LIBS COND_SOUND_ALSA_TRUE COND_SOUND_ALSA_FALSE COND_SOUND_ESD_TRUE COND_SOUND_ESD_FALSE COND_NATIVE_SOUND_TRUE COND_NATIVE_SOUND_FALSE COND_PURE_JAVA_MATH_TRUE COND_PURE_JAVA_MATH_FALSE MATH_LIB INCLUDED_EXTENSIONS PROFILE XML2_CONFIG XML_CFLAGS XML_LIBS XSLT_CONFIG XSLT_CFLAGS XSLT_LIBS COND_LIBXMLJ_TRUE COND_LIBXMLJ_FALSE JAVA uudecode JAVAC ANTLR ANTLR_JAR COND_GJDOC_TRUE COND_GJDOC_FALSE USE_PRECOMPILED_RT_JAR_TRUE USE_PRECOMPILED_RT_JAR_FALSE PATH_TO_RT_JAR DLOPEN_JAVA_LIBS OPT_DLOPEN_JAVA_LIBS KLIBFLAGS KVMBINFLAGS KVMLIBFLAGS BINRELOC_CFLAGS ENABLE_BINRELOC_TRUE ENABLE_BINRELOC_FALSE KAFFEH MAKE_KAFFEH toolslibdir jredir jrebindir jrelibdir nativedir securitydir PATHSEP DIRSEP kaffe_TRANSF kaffeh_TRANSF kaffebin_TRANSF CFLAGS_WITHOUT_PG LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT abssrcdir CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS LIBLTDL CCLD MKINSTALLDIRS USE_NLS MSGFMT GMSGFMT XGETTEXT MSGMERGE LIBICONV LTLIBICONV INTLLIBS LIBINTL LTLIBINTL POSUB MAY_RUN_PO_TRUE MAY_RUN_PO_FALSE REGEN_FORWARD CONFIG_MD_H CONFIG_CALLKAFFEEXCEPTION_H KAFFEVM_MD_C CONFIG_JIT_MD_H KAFFEVM_JIT_DEF KAFFEVM_ICODE_H HAVE_CONFIG_JIT_MD_H USE_JIT_TRUE USE_JIT_FALSE ENGINE_NAME BCEL_JAR HAVE_BCEL_TRUE HAVE_BCEL_FALSE ENABLE_JVMPI_TRUE ENABLE_JVMPI_FALSE ENABLE_XPROF_TRUE ENABLE_XPROF_FALSE CONFIG_XPROFILE_MD_H JAVAC_FLAGS NEED_LIBXPROF_TRUE NEED_LIBXPROF_FALSE CFLAGS_PG SUN_COMPAT_TRUE SUN_COMPAT_FALSE THREAD_DIR acx_pthread_config PTHREAD_CC PTHREAD_LIBS PTHREAD_CFLAGS SEMAPHORE_LIB VM_LIBS USE_PRECOMPILED_RT_JAR_TRUE USE_PRECOMPILED_RT_JAR_FALSE PATH_TO_RT_JAR JIKESPROG JIKES KAFFEVM_TRAMPOLINES_C JAVA_LIBS with_engine THREAD_SYSTEM KPREFIX KAFFE_ARCHOS ZIP MKTEMP JASMIN HAVE_ZIP_TRUE HAVE_ZIP_FALSE HAVE_JIKES_TRUE HAVE_JIKES_FALSE HAVE_MKTEMP_TRUE HAVE_MKTEMP_FALSE HAVE_JASMIN_TRUE HAVE_JASMIN_FALSE KAFFE_LIBS M_LIBS NET_LIBS ZIP_LIBS LIBADD_GMP USE_GMP SECURITY_LIBS GC_NAME subdirs BOEHMGC_SPECIFIC_FLAGS HAVE_GCJ_SUPPORT_TRUE HAVE_GCJ_SUPPORT_FALSE LIBOBJS USE_COMPAT_IFADDRS_TRUE USE_COMPAT_IFADDRS_FALSE GTK_CAIRO_TRUE GTK_CAIRO_FALSE COND_NATIVE_AWT_TRUE COND_NATIVE_AWT_FALSE COND_KAFFE_X_AWT_TRUE COND_KAFFE_X_AWT_FALSE X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS AWT_LIBS COND_KAFFE_QT_AWT_TRUE COND_KAFFE_QT_AWT_FALSE MOC UIC QEMBED QT_CXXFLAGS QT_LDADD QT_GUILINK QASSISTANTCLIENT_LDADD COND_CLASSPATH_GTK_AWT_TRUE COND_CLASSPATH_GTK_AWT_FALSE PKG_CONFIG GTK_CFLAGS GTK_LIBS CAIRO_CFLAGS CAIRO_LIBS PANGOFT2_CFLAGS PANGOFT2_LIBS ALSA_CFLAGS ALSA_LIBS ESD_CONFIG ESD_CFLAGS ESD_LIBS COND_SOUND_ALSA_TRUE COND_SOUND_ALSA_FALSE COND_SOUND_ESD_TRUE COND_SOUND_ESD_FALSE COND_NATIVE_SOUND_TRUE COND_NATIVE_SOUND_FALSE COND_PURE_JAVA_MATH_TRUE COND_PURE_JAVA_MATH_FALSE MATH_LIB INCLUDED_EXTENSIONS PROFILE XML2_CONFIG XML_CFLAGS XML_LIBS XSLT_CONFIG XSLT_CFLAGS XSLT_LIBS COND_LIBXMLJ_TRUE COND_LIBXMLJ_FALSE JAVA uudecode JAVAC ANTLR ANTLR_JAR COND_GJDOC_TRUE COND_GJDOC_FALSE DLOPEN_JAVA_LIBS OPT_DLOPEN_JAVA_LIBS KLIBFLAGS KVMBINFLAGS KVMLIBFLAGS BINRELOC_CFLAGS ENABLE_BINRELOC_TRUE ENABLE_BINRELOC_FALSE KAFFEH MAKE_KAFFEH toolslibdir jredir jrebindir jrelibdir nativedir securitydir PATHSEP DIRSEP kaffe_TRANSF kaffeh_TRANSF kaffebin_TRANSF CFLAGS_WITHOUT_PG LTLIBOBJS'
 ac_subst_files='cpu_os_frag cpu_frag engine_frag threads_frag gc_frag'
 
 # Initialize some variables set by options.
@@ -1127,6 +1127,7 @@ Optional Packages:
                           [default=unix-pthreads]
   --with-gc=GC            Force use given execution engine (kaffe-gc or
                           boehm-gc)
+  --with-rt-jar=ABS.PATH  use precompiled kaffe class library
   --with-jikes<=JIKES>    Define to use jikes compiler [default=yes]. If
                           yes, use jikes +Pno-switchcheck +Pno-shadow +E
   --with-libffi           Use libffi for sysdepCallMethod
@@ -1160,7 +1161,6 @@ Optional Packages:
   --with-xml-exec-prefix=PFX Exec prefix where libxml is installed (optional)
   --with-xslt-prefix=PFX   Prefix where libxslt is installed (optional)
   --with-xslt-exec-prefix=PFX Exec prefix where libxslt is installed (optional)
-  --with-rt-jar=ABS.PATH  use precompiled kaffe class library
   --with-jni-library-path=dir
                           additional directories to search for native jni
                           libraries
@@ -28629,6 +28629,48 @@ if test "${with_gc+set}" = set; then
 fi;
 
 
+# Check whether --with-rt_jar or --without-rt_jar was given.
+if test "${with_rt_jar+set}" = set; then
+  withval="$with_rt_jar"
+
+fi;
+
+case "$with_rt_jar" in
+"")
+	if test -f $abssrcdir/libraries/javalib/rt-precompiled.jar; then
+		use_rt_jar=true
+		PATH_TO_RT_JAR=$abssrcdir/libraries/javalib/rt-precompiled.jar
+	else
+		use_rt_jar=false
+	fi
+	;;
+"no" )
+	use_rt_jar=false
+	;;
+"yes")
+	{ { echo "$as_me:$LINENO: error: Please suply an absolute path to a precompiled rt.jar from this version of kaffe" >&5
+echo "$as_me: error: Please suply an absolute path to a precompiled rt.jar from this version of kaffe" >&2;}
+   { (exit 1); exit 1; }; }
+	;;
+*)
+	use_rt_jar=true
+	PATH_TO_RT_JAR=$with_rt_jar
+	;;
+esac;
+
+
+
+if test x$use_rt_jar = xtrue; then
+  USE_PRECOMPILED_RT_JAR_TRUE=
+  USE_PRECOMPILED_RT_JAR_FALSE='#'
+else
+  USE_PRECOMPILED_RT_JAR_TRUE='#'
+  USE_PRECOMPILED_RT_JAR_FALSE=
+fi
+
+
+
+
 # Extract the first word of "jikes", so it can be a program name with args.
 set dummy jikes; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -28679,18 +28721,28 @@ echo $ECHO_N "checking whether to use jikes... $ECHO_C" >&6
 case $with_jikes in
 yes)
 	if test x"$JIKESPROG" == x"" ; then
-	  { { echo "$as_me:$LINENO: error: No jikes compiler found. It is required to build Kaffe's class library. Recommended is jikes version 1.21 or higher." >&5
+	  if  test x$use_rt_jar = xtrue ; then
+	    { echo "$as_me:$LINENO: WARNING: No jikes compiler found. It is required to build the regression tests. Recommended is jikes version 1.21 or higher." >&5
+echo "$as_me: WARNING: No jikes compiler found. It is required to build the regression tests. Recommended is jikes version 1.21 or higher." >&2;}
+          else
+	    { { echo "$as_me:$LINENO: error: No jikes compiler found. It is required to build Kaffe's class library. Recommended is jikes version 1.21 or higher." >&5
 echo "$as_me: error: No jikes compiler found. It is required to build Kaffe's class library. Recommended is jikes version 1.21 or higher." >&2;}
    { (exit 1); exit 1; }; }
+          fi
 	fi
 	JIKES="$JIKESPROG +Pno-switchcheck +Pno-shadow +E"
 	use_jikes="yes ($JIKES)"
 	;;
 no)
 	use_jikes="no"
-	{ { echo "$as_me:$LINENO: error: You have to use jikes 1.21 or higher to build kaffe's class library, or to pass a different external java compiler to configure script." >&5
+	  if  test x$use_rt_jar = xtrue ; then
+	    { echo "$as_me:$LINENO: WARNING: You have to use jikes 1.21 or higher to build kaffe's regression tests, or to pass a different external java compiler to configure script." >&5
+echo "$as_me: WARNING: You have to use jikes 1.21 or higher to build kaffe's regression tests, or to pass a different external java compiler to configure script." >&2;}
+          else
+	    { { echo "$as_me:$LINENO: error: You have to use jikes 1.21 or higher to build kaffe's class library, or to pass a different external java compiler to configure script." >&5
 echo "$as_me: error: You have to use jikes 1.21 or higher to build kaffe's class library, or to pass a different external java compiler to configure script." >&2;}
    { (exit 1); exit 1; }; }
+          fi
 	;;
 *)
 	JIKES="$with_jikes"
@@ -58338,7 +58390,7 @@ EOF
 if uudecode$EXEEXT Test.uue; then
         ac_cv_prog_uudecode_base64=yes
 else
-        echo "configure: 58341: uudecode had trouble decoding base 64 file 'Test.uue'" >&5
+        echo "configure: 58393: uudecode had trouble decoding base 64 file 'Test.uue'" >&5
         echo "configure: failed file was:" >&5
         cat Test.uue >&5
         ac_cv_prog_uudecode_base64=no
@@ -58456,7 +58508,7 @@ else
 JAVA_TEST=Test.java
 CLASS_TEST=Test.class
 cat << \EOF > $JAVA_TEST
-/* #line 58459 "configure" */
+/* #line 58511 "configure" */
 public class Test {
 }
 EOF
@@ -58493,7 +58545,7 @@ JAVA_TEST=Test.java
 CLASS_TEST=Test.class
 TEST=Test
 cat << \EOF > $JAVA_TEST
-/* [#]line 58496 "configure" */
+/* [#]line 58548 "configure" */
 public class Test {
 public static void main (String args[]) {
         System.exit (0);
@@ -58590,48 +58642,6 @@ else
   COND_GJDOC_TRUE='#'
   COND_GJDOC_FALSE=
 fi
-
-
-
-# Check whether --with-rt_jar or --without-rt_jar was given.
-if test "${with_rt_jar+set}" = set; then
-  withval="$with_rt_jar"
-
-fi;
-
-case "$with_rt_jar" in
-"")
-	if test -f $abssrcdir/libraries/javalib/rt-precompiled.jar; then
-		use_rt_jar=true
-		PATH_TO_RT_JAR=$abssrcdir/libraries/javalib/rt-precompiled.jar
-	else
-		use_rt_jar=false
-	fi
-	;;
-"no" )
-	use_rt_jar=false
-	;;
-"yes")
-	{ { echo "$as_me:$LINENO: error: Please suply an absolute path to a precompiled rt.jar from this version of kaffe" >&5
-echo "$as_me: error: Please suply an absolute path to a precompiled rt.jar from this version of kaffe" >&2;}
-   { (exit 1); exit 1; }; }
-	;;
-*)
-	use_rt_jar=true
-	PATH_TO_RT_JAR=$with_rt_jar
-	;;
-esac;
-
-
-
-if test x$use_rt_jar = xtrue; then
-  USE_PRECOMPILED_RT_JAR_TRUE=
-  USE_PRECOMPILED_RT_JAR_FALSE='#'
-else
-  USE_PRECOMPILED_RT_JAR_TRUE='#'
-  USE_PRECOMPILED_RT_JAR_FALSE=
-fi
-
 
 
 JAVA_LIBS=" \
@@ -59703,6 +59713,13 @@ echo "$as_me: error: conditional \"SUN_COMPAT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${USE_PRECOMPILED_RT_JAR_TRUE}" && test -z "${USE_PRECOMPILED_RT_JAR_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"USE_PRECOMPILED_RT_JAR\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"USE_PRECOMPILED_RT_JAR\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${HAVE_ZIP_TRUE}" && test -z "${HAVE_ZIP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_ZIP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -59826,13 +59843,6 @@ if test -z "${COND_GJDOC_TRUE}" && test -z "${COND_GJDOC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"COND_GJDOC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"COND_GJDOC\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-if test -z "${USE_PRECOMPILED_RT_JAR_TRUE}" && test -z "${USE_PRECOMPILED_RT_JAR_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"USE_PRECOMPILED_RT_JAR\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"USE_PRECOMPILED_RT_JAR\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -60610,6 +60620,9 @@ s,@PTHREAD_LIBS@,$PTHREAD_LIBS,;t t
 s,@PTHREAD_CFLAGS@,$PTHREAD_CFLAGS,;t t
 s,@SEMAPHORE_LIB@,$SEMAPHORE_LIB,;t t
 s,@VM_LIBS@,$VM_LIBS,;t t
+s,@USE_PRECOMPILED_RT_JAR_TRUE@,$USE_PRECOMPILED_RT_JAR_TRUE,;t t
+s,@USE_PRECOMPILED_RT_JAR_FALSE@,$USE_PRECOMPILED_RT_JAR_FALSE,;t t
+s,@PATH_TO_RT_JAR@,$PATH_TO_RT_JAR,;t t
 s,@JIKESPROG@,$JIKESPROG,;t t
 s,@JIKES@,$JIKES,;t t
 s,@KAFFEVM_TRAMPOLINES_C@,$KAFFEVM_TRAMPOLINES_C,;t t
@@ -60704,9 +60717,6 @@ s,@ANTLR@,$ANTLR,;t t
 s,@ANTLR_JAR@,$ANTLR_JAR,;t t
 s,@COND_GJDOC_TRUE@,$COND_GJDOC_TRUE,;t t
 s,@COND_GJDOC_FALSE@,$COND_GJDOC_FALSE,;t t
-s,@USE_PRECOMPILED_RT_JAR_TRUE@,$USE_PRECOMPILED_RT_JAR_TRUE,;t t
-s,@USE_PRECOMPILED_RT_JAR_FALSE@,$USE_PRECOMPILED_RT_JAR_FALSE,;t t
-s,@PATH_TO_RT_JAR@,$PATH_TO_RT_JAR,;t t
 s,@DLOPEN_JAVA_LIBS@,$DLOPEN_JAVA_LIBS,;t t
 s,@OPT_DLOPEN_JAVA_LIBS@,$OPT_DLOPEN_JAVA_LIBS,;t t
 s,@KLIBFLAGS@,$KLIBFLAGS,;t t
