2007-07-02  Dalibor Topic  <robilad@kaffe.org>
        * configure.ac : Check if zlib is recent enough (1.2.3, or later).

        Reported by:  Kiyo Inaba <inaba@src.ricoh.co.jp>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -47401,6 +47401,32 @@ if test x"$ac_cv_lib_z_deflate" != x"yes" ; then
 echo "$as_me: error: Can't find system zlib or can't find function deflate in it" >&2;}
    { (exit 1); exit 1; }; }
 fi
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <zlib.h>
+
+#if ZLIB_VERNUM >= 0x1230
+  yes
+#endif
+
+_ACEOF
+if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
+  $EGREP "yes" >/dev/null 2>&1; then
+  is_recent_zlib=yes
+else
+  is_recent_zlib=no
+fi
+rm -f conftest*
+
+if test x"$is_recent_zlib" != x"yes" ; then
+  { { echo "$as_me:$LINENO: error: Can't find zlib 1.2.3 or later" >&5
+echo "$as_me: error: Can't find zlib 1.2.3 or later" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 
 
