Patched libtool for darwin
2004-07-22  Dalibor Topic  <robilad@kaffe.org>

        * Makefile.am:
        (EXTRA_DIST) Added
        developers/patch-libtool-cdpath-zsh.patch.

        * configure.ac:
        Use AC_CHECK_HEADERS to check for gmp header.

        * developers/autogen.sh
        Apply cdpath patch for libtool.

        * developers/patch-libtool-cdpath-zsh.patch:
        New file. Fix CDPATH with zsh for darwin.

        Patch by: Peter O'Gorman <peter@pogma.com>
        Reported by: Riccardo Mottola <rmottola@users.sf.net>

        * Makefile.in,
        configure,
        libltdl/acinclude.m4,
        libltdl/configure,
        libltdl/ltmain.sh,
        libraries/javalib/Makefile.am,
        libraries/javalib/Makefile.in,
        m4/libtool.m4:
        Regeenrated.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -303,8 +303,8 @@ fi
 
 # The HP-UX ksh and POSIX shell print the target directory to stdout
 # if CDPATH is set.
-if test "X${CDPATH+set}" = Xset; then CDPATH=:; export CDPATH; fi
-
+#if test "X${CDPATH+set}" = Xset; then CDPATH=:; export CDPATH; fi
+(unset CDPATH) >/dev/null 2>&1 && unset CDPATH
 if test -z "$ECHO"; then
 if test "X${echo_test_string+set}" != Xset; then
 # find a string as large as possible, as long as the shell can cope with it
@@ -14264,7 +14264,7 @@ Xsed="$SED -e s/^X//"
 # The HP-UX ksh and POSIX shell print the target directory to stdout
 # if CDPATH is set.
 if test "X\${CDPATH+set}" = Xset; then CDPATH=:; export CDPATH; fi
-
+(unset CDPATH) >/dev/null 2>&1 && unset CDPATH
 # The names of the tagged configurations supported by this script.
 available_tags=
 
@@ -53840,18 +53840,22 @@ echo "$as_me: error: Could not find GNU MP library.  Install the gmp development
    { (exit 1); exit 1; }; }
 		fi
 	fi
-	if test "${ac_cv_header_gmp_h+set}" = set; then
-  echo "$as_me:$LINENO: checking for gmp.h" >&5
-echo $ECHO_N "checking for gmp.h... $ECHO_C" >&6
-if test "${ac_cv_header_gmp_h+set}" = set; then
+
+for ac_header in gmp.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 fi
-echo "$as_me:$LINENO: result: $ac_cv_header_gmp_h" >&5
-echo "${ECHO_T}$ac_cv_header_gmp_h" >&6
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
 else
   # Is the header compilable?
-echo "$as_me:$LINENO: checking gmp.h usability" >&5
-echo $ECHO_N "checking gmp.h usability... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -53859,7 +53863,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 $ac_includes_default
-#include <gmp.h>
+#include <$ac_header>
 _ACEOF
 rm -f conftest.$ac_objext
 if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
@@ -53895,15 +53899,15 @@ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
 echo "${ECHO_T}$ac_header_compiler" >&6
 
 # Is the header present?
-echo "$as_me:$LINENO: checking gmp.h presence" >&5
-echo $ECHO_N "checking gmp.h presence... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <gmp.h>
+#include <$ac_header>
 _ACEOF
 if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
@@ -53937,25 +53941,25 @@ echo "${ECHO_T}$ac_header_preproc" >&6
 # So?  What about this header?
 case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
   yes:no: )
-    { echo "$as_me:$LINENO: WARNING: gmp.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: gmp.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: gmp.h: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: gmp.h: proceeding with the compiler's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
     ac_header_preproc=yes
     ;;
   no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: gmp.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: gmp.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: gmp.h:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: gmp.h:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: gmp.h: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: gmp.h: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: gmp.h:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: gmp.h:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: gmp.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: gmp.h: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: gmp.h: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: gmp.h: in the future, the compiler will take precedence" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}
     (
       cat <<\_ASBOX
 ## ------------------------------ ##
@@ -53966,25 +53970,29 @@ _ASBOX
       sed "s/^/$as_me: WARNING:     /" >&2
     ;;
 esac
-echo "$as_me:$LINENO: checking for gmp.h" >&5
-echo $ECHO_N "checking for gmp.h... $ECHO_C" >&6
-if test "${ac_cv_header_gmp_h+set}" = set; then
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_cv_header_gmp_h=$ac_header_preproc
+  eval "$as_ac_Header=\$ac_header_preproc"
 fi
-echo "$as_me:$LINENO: result: $ac_cv_header_gmp_h" >&5
-echo "${ECHO_T}$ac_cv_header_gmp_h" >&6
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
 
 fi
-if test $ac_cv_header_gmp_h = yes; then
-  pure_java_math=false
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+ pure_java_math=false
 else
-  { { echo "$as_me:$LINENO: error: Found GNU MP library, but can't find gmp.h.  Install the gmp development package, or pass --enable-pure-java-math to configure." >&5
-echo "$as_me: error: Found GNU MP library, but can't find gmp.h.  Install the gmp development package, or pass --enable-pure-java-math to configure." >&2;}
+  { { echo "$as_me:$LINENO: error: Found GNU MP library, but can't find gmp.h.  Install the gmp development package, or pass --enable-pure-java-math to  configure." >&5
+echo "$as_me: error: Found GNU MP library, but can't find gmp.h.  Install the gmp development package, or pass --enable-pure-java-math to  configure." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
+done
 
 
 
