Resynced with gjdoc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1177,6 +1177,8 @@ Optional Packages:
   --with-xml-exec-prefix=PFX Exec prefix where libxml is installed (optional)
   --with-xslt-prefix=PFX   Prefix where libxslt is installed (optional)
   --with-xslt-exec-prefix=PFX Exec prefix where libxslt is installed (optional)
+  --with-antlr-jar=file   Use ANTLR from the specified jar file. ANTLR is
+                          required for gjdoc
   --with-jni-library-path=dir
                           additional directories to search for native jni
                           libraries
@@ -10069,7 +10071,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 10072 "configure"' > conftest.$ac_ext
+  echo '#line 10074 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -11426,7 +11428,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:11429:" \
+echo "$as_me:11431:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -12499,11 +12501,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12502: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12504: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12506: \$? = $ac_status" >&5
+   echo "$as_me:12508: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -12754,11 +12756,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12757: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12759: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12761: \$? = $ac_status" >&5
+   echo "$as_me:12763: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -12814,11 +12816,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12817: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12819: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12821: \$? = $ac_status" >&5
+   echo "$as_me:12823: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15018,7 +15020,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 15021 "configure"
+#line 15023 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15116,7 +15118,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 15119 "configure"
+#line 15121 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17340,11 +17342,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17343: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17345: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17347: \$? = $ac_status" >&5
+   echo "$as_me:17349: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -17400,11 +17402,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17403: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17405: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17407: \$? = $ac_status" >&5
+   echo "$as_me:17409: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18767,7 +18769,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18770 "configure"
+#line 18772 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18865,7 +18867,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18868 "configure"
+#line 18870 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19720,11 +19722,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19723: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19725: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19727: \$? = $ac_status" >&5
+   echo "$as_me:19729: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -19780,11 +19782,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19783: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19785: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:19787: \$? = $ac_status" >&5
+   echo "$as_me:19789: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21844,11 +21846,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:21847: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:21849: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:21851: \$? = $ac_status" >&5
+   echo "$as_me:21853: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -22099,11 +22101,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:22102: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:22104: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:22106: \$? = $ac_status" >&5
+   echo "$as_me:22108: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -22159,11 +22161,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:22162: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:22164: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:22166: \$? = $ac_status" >&5
+   echo "$as_me:22168: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -24363,7 +24365,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 24366 "configure"
+#line 24368 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -24461,7 +24463,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 24464 "configure"
+#line 24466 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -51724,6 +51726,15 @@ fi
 
 
 
+
+# Check whether --with-antlr-jar or --without-antlr-jar was given.
+if test "${with_antlr_jar+set}" = set; then
+  withval="$with_antlr_jar"
+   ANTLR_JAR=$withval
+else
+   ANTLR_JAR="$ANTLR_JAR"
+fi;
+
 # Check whether --enable-gjdoc or --disable-gjdoc was given.
 if test "${enable_gjdoc+set}" = set; then
   enableval="$enable_gjdoc"
@@ -51741,10 +51752,11 @@ echo $ECHO_N "checking for antlr 2.7.1 or better... $ECHO_C" >&6
                       ANTLR_JAR=$antlr_lib_home/antlr.jar
 	fi
   done
-  test -z $ANTLR_JAR && \
-        { { echo "$as_me:$LINENO: error: no suitable antlr.jar found for version 2.7.1" >&5
-echo "$as_me: error: no suitable antlr.jar found for version 2.7.1" >&2;}
-   { (exit 1); exit 1; }; }
+  test -f $ANTLR_JAR || { { echo "$as_me:$LINENO: error: specified ANTLR jar file $ANTLR_JAR not found." >&5
+echo "$as_me: error: specified ANTLR jar file $ANTLR_JAR not found." >&2;}
+   { (exit 1); exit 1; }; } \
+  	&& { echo "$as_me:$LINENO: using ANTLR parser generator in $ANTLR_JAR" >&5
+echo "$as_me: using ANTLR parser generator in $ANTLR_JAR" >&6;}
   echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
@@ -52646,6 +52658,8 @@ subdirs="$subdirs libltdl"
 
           ac_config_files="$ac_config_files tools/Makefile"
 
+          ac_config_files="$ac_config_files tools/gjdoc/javalib/version.properties"
+
           ac_config_files="$ac_config_files tools/gjdoc/Makefile"
 
           ac_config_files="$ac_config_files tools/gjdoc/javalib/Makefile"
@@ -53526,6 +53540,7 @@ do
   "kaffe/scripts/compat/javadoc" ) CONFIG_FILES="$CONFIG_FILES kaffe/scripts/compat/javadoc" ;;
   "po/Makefile.in" ) CONFIG_FILES="$CONFIG_FILES po/Makefile.in" ;;
   "tools/Makefile" ) CONFIG_FILES="$CONFIG_FILES tools/Makefile" ;;
+  "tools/gjdoc/javalib/version.properties" ) CONFIG_FILES="$CONFIG_FILES tools/gjdoc/javalib/version.properties" ;;
   "tools/gjdoc/Makefile" ) CONFIG_FILES="$CONFIG_FILES tools/gjdoc/Makefile" ;;
   "tools/gjdoc/javalib/Makefile" ) CONFIG_FILES="$CONFIG_FILES tools/gjdoc/javalib/Makefile" ;;
   "test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
