fix for #76
2006-11-19  Dalibor Topic  <robilad@kaffe.org>

        Fix for #76.

        * configure.ac: Check if lib(un)gif header is installed,
        when building kaffe X AWT and error out if it isn't.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -50444,6 +50444,10 @@ GIF_LIBS=`echo "$LIBS" | sed "s% $KSAVE_LIBS$%%"`
 LIBS="$KSAVE_LIBS"
 
            fi
+	else
+	   { { echo "$as_me:$LINENO: error: No gif_lib.h found. Please install libungif or libgif." >&5
+echo "$as_me: error: No gif_lib.h found. Please install libungif or libgif." >&2;}
+   { (exit 1); exit 1; }; }
         fi
 
 	LIBS=$OLIBS
