Resynced with GNU Classpath: cairo updates

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -48345,23 +48345,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for cairo" >&5
-echo $ECHO_N "checking for cairo... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for cairo >= 0.5.0" >&5
+echo $ECHO_N "checking for cairo >= 0.5.0... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "cairo" ; then
+        if $PKG_CONFIG --exists "cairo >= 0.5.0" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking CAIRO_CFLAGS" >&5
 echo $ECHO_N "checking CAIRO_CFLAGS... $ECHO_C" >&6
-            CAIRO_CFLAGS=`$PKG_CONFIG --cflags "cairo"`
+            CAIRO_CFLAGS=`$PKG_CONFIG --cflags "cairo >= 0.5.0"`
             echo "$as_me:$LINENO: result: $CAIRO_CFLAGS" >&5
 echo "${ECHO_T}$CAIRO_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking CAIRO_LIBS" >&5
 echo $ECHO_N "checking CAIRO_LIBS... $ECHO_C" >&6
-            CAIRO_LIBS=`$PKG_CONFIG --libs "cairo"`
+            CAIRO_LIBS=`$PKG_CONFIG --libs "cairo >= 0.5.0"`
             echo "$as_me:$LINENO: result: $CAIRO_LIBS" >&5
 echo "${ECHO_T}$CAIRO_LIBS" >&6
         else
@@ -48369,7 +48369,7 @@ echo "${ECHO_T}$CAIRO_LIBS" >&6
             CAIRO_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            CAIRO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "cairo"`
+            CAIRO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "cairo >= 0.5.0"`
             echo $CAIRO_PKG_ERRORS
         fi
 
@@ -48384,8 +48384,8 @@ echo "${ECHO_T}$CAIRO_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (cairo) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (cairo) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (cairo >= 0.5.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (cairo >= 0.5.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
