2003-07-26 Timothy S. Stack <stack@cs.utah.edu>
	* configure.in:
	Add JVMPI stuff (--enable-jvmpi, makefile, etc...)

	* include/Makefile.am:
	Add jvmpi.h to the list of include_HEADERS.

	* include/errors.h:
	Make IncompatibleClassChangeError take a message parameter.

	* include/jni.h:
	Add JVMPI defines.

	* include/jvmpi.h:
	Added

	* kaffe/Makefile.am:
	Added jvmpi subdir.

	* kaffe/jvmpi/Makefile.am,
	kaffe/jvmpi/jvmpi_kaffe.c,
	kaffe/jvmpi/jvmpi_kaffe.h:
	Added to implement jvmpi stuff.

	* kaffe/kaffe/Makefile.am:
	Add jvmpi to list of includes and add jvmpi library.

	* kaffe/kaffevm/Makefile.am:
	Add jvmpi to list of includes.

	* kaffe/kaffevm/classMethod.h:
	Make a slot for a field's signature in struct_fields.

	* kaffe/kaffevm/classMethod.c:
	Add jvmpi events.  Fields now have a separate slot for their
	signature instead of combining it with FIELD_TYPE().  Use
	per-thread JNIEnv.

	* kaffe/kaffevm/exception.c:
	Remove requirement that nextFrame must be called on stack produced
	from the current thread.

	* kaffe/kaffevm/gc.h:
	Add function pointers for enabling/disabling gc.

	* kaffe/kaffevm/gcFuncs.c:
	Add jvmpi events.  Handle separate slot for signature in fields.
	Use per-thread JNIEnv.

	* kaffe/kaffevm/gcRefs.c:
	jthread_getcookie() -> jthread_get_data().

	* kaffe/kaffevm/jni.c:
	Add JVMPI events.  JNIEnv pointers are now per-thread.

	* kaffe/kaffevm/kaffe.def:
	Make sure invokevirtual/invokespecial are not called on interface
	classes.

	* kaffe/kaffevm/locks.c:
	Add JVMPI events.

	* kaffe/kaffevm/object.c:
	Add JVMPI events.

	* kaffe/kaffevm/soft.[ch]:
	Add soft_incompatibleclasschange function for throwing
	IncompatibleClassChangeErrors.

	* kaffe/kaffevm/support.h:
	Add BITMAP_BYTE_SIZE, BITMAP_CLEAR, and BITMAP_ISSET macros.

	* kaffe/kaffevm/thread.c:
	JNIEnv pointers are now per-thread.  jthread_getcookie() ->
	jthread_get_data().  Added JVMPI events.

	* kaffe/kaffevm/thread.h:
	Added THREAD_JNIENV() macro for getting the JNIEnv pointer for the
	current thread.

	* kaffe/kaffevm/threadData.h:
	Added to hold per-thread data.

	* kaffe/kaffevm/jit3/Makefile.am:
	Added jvmpi to the list of includes.

	* kaffe/kaffevm/jit3/codeproto.h,
	kaffe/kaffevm/jit3/icode.c:
	Added softcall_incompatibleclasschange().

	* kaffe/kaffevm/jit3/machine.c:
	Added JVMPI events.

	* kaffe/kaffevm/mem/gc-incremental.c:
	Added JVMPI events and functions for enabling/disabling the GC.

	* kaffe/kaffevm/systems/unix-jthreads/jthread.c,
	kaffe/kaffevm/systems/unix-jthreads/jthread.h:
	The jthread_getcookie() macro has been changed to
	jthread_get_data() which returns the threadData structure defined
	in the main kaffe code body.  Added resource usage statistics and
	other functions for reflecting on a threads state.  Added ability
	to suspend/resume threads (experimental).

	* kaffe/kaffevm/systems/unix-jthreads/lock-impl.h:
	Added missing jcondvar_broadcast() proto.

	* kaffe/kaffevm/systems/unix-pthreads/thread-impl.c,
	kaffe/kaffevm/systems/unix-pthreads/thread-impl.c:
	Update for jthread_getcookie() -> jthread_get_data() change.

	* libraries/clib/native/Makefile.am:
	Added jvmpi to list of includes.

	* libraries/clib/native/Object.c:
	Added JVMPI events.

	* libraries/clib/native/ObjectStreamClassImpl.c:
	Update for signature change in field structs.

	* test/internal/Makefile.am:
	Add jvmpi to the list of includes and libraries.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -466,7 +466,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all libltdl"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT abssrcdir CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS LIBLTDL CCLD REGEN_FORWARD CONFIG_MD_H KAFFEVM_MD_C CONFIG_JIT_MD_H KAFFEVM_JIT_DEF KAFFEVM_ICODE_H HAVE_CONFIG_JIT_MD_H USE_JIT_TRUE USE_JIT_FALSE ENGINE_NAME DNSJAVA_JAR HAVE_DNSJAVA_TRUE HAVE_DNSJAVA_FALSE ENABLE_XPROF_TRUE ENABLE_XPROF_FALSE CONFIG_XPROFILE_MD_H NEED_LIBXPROF_TRUE NEED_LIBXPROF_FALSE SUN_COMPAT_TRUE SUN_COMPAT_FALSE THREAD_DIR JIKESPROG JIKES KAFFEVM_TRAMPOLINES_C KVER JAVA_LIBS with_engine THREAD_SYSTEM KPREFIX KAFFE_ARCHOS ZIP MKTEMP HAVE_ZIP_TRUE HAVE_ZIP_FALSE HAVE_JIKES_TRUE HAVE_JIKES_FALSE HAVE_MKTEMP_TRUE HAVE_MKTEMP_FALSE KAFFE_LIBS M_LIBS VM_LIBS NET_LIBS ZIP_LIBS MATH_LIBS SECURITY_LIBS X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS AWT_LIBS HAVE_GCJ_SUPPORT_TRUE HAVE_GCJ_SUPPORT_FALSE LIBOBJS LIBICONV LTLIBICONV USE_COMPAT_IFADDRS_TRUE USE_COMPAT_IFADDRS_FALSE MOC UIC QEMBED QT_CXXFLAGS QT_LDADD QT_GUILINK AWT_DIR COND_SOUND_ALSA_TRUE COND_SOUND_ALSA_FALSE COND_SOUND_ESD_TRUE COND_SOUND_ESD_FALSE COND_PURE_JAVA_MATH_TRUE COND_PURE_JAVA_MATH_FALSE MATH_LIB INCLUDED_EXTENSIONS PROFILE USE_PRECOMPILED_RT_JAR_TRUE USE_PRECOMPILED_RT_JAR_FALSE PATH_TO_RT_JAR DLOPEN_JAVA_LIBS KLIBFLAGS KVMBINFLAGS KVMLIBFLAGS KAFFEH MAKE_KAFFEH toolslibdir jredir jrebindir jrelibdir nativedir securitydir PATHSEP DIRSEP kaffe_TRANSF kaffeh_TRANSF kaffebin_TRANSF CFLAGS_WITHOUT_PG subdirs LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT abssrcdir CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS LIBLTDL CCLD REGEN_FORWARD CONFIG_MD_H KAFFEVM_MD_C CONFIG_JIT_MD_H KAFFEVM_JIT_DEF KAFFEVM_ICODE_H HAVE_CONFIG_JIT_MD_H USE_JIT_TRUE USE_JIT_FALSE ENGINE_NAME ENABLE_JVMPI_TRUE ENABLE_JVMPI_FALSE DNSJAVA_JAR HAVE_DNSJAVA_TRUE HAVE_DNSJAVA_FALSE ENABLE_XPROF_TRUE ENABLE_XPROF_FALSE CONFIG_XPROFILE_MD_H NEED_LIBXPROF_TRUE NEED_LIBXPROF_FALSE SUN_COMPAT_TRUE SUN_COMPAT_FALSE THREAD_DIR JIKESPROG JIKES KAFFEVM_TRAMPOLINES_C KVER JAVA_LIBS with_engine THREAD_SYSTEM KPREFIX KAFFE_ARCHOS ZIP MKTEMP HAVE_ZIP_TRUE HAVE_ZIP_FALSE HAVE_JIKES_TRUE HAVE_JIKES_FALSE HAVE_MKTEMP_TRUE HAVE_MKTEMP_FALSE KAFFE_LIBS M_LIBS VM_LIBS NET_LIBS ZIP_LIBS MATH_LIBS SECURITY_LIBS X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS AWT_LIBS HAVE_GCJ_SUPPORT_TRUE HAVE_GCJ_SUPPORT_FALSE LIBOBJS LIBICONV LTLIBICONV USE_COMPAT_IFADDRS_TRUE USE_COMPAT_IFADDRS_FALSE MOC UIC QEMBED QT_CXXFLAGS QT_LDADD QT_GUILINK AWT_DIR COND_SOUND_ALSA_TRUE COND_SOUND_ALSA_FALSE COND_SOUND_ESD_TRUE COND_SOUND_ESD_FALSE COND_PURE_JAVA_MATH_TRUE COND_PURE_JAVA_MATH_FALSE MATH_LIB INCLUDED_EXTENSIONS PROFILE USE_PRECOMPILED_RT_JAR_TRUE USE_PRECOMPILED_RT_JAR_FALSE PATH_TO_RT_JAR DLOPEN_JAVA_LIBS KLIBFLAGS KVMBINFLAGS KVMLIBFLAGS KAFFEH MAKE_KAFFEH toolslibdir jredir jrebindir jrelibdir nativedir securitydir PATHSEP DIRSEP kaffe_TRANSF kaffeh_TRANSF kaffebin_TRANSF CFLAGS_WITHOUT_PG subdirs LTLIBOBJS'
 ac_subst_files='cpu_os_frag cpu_frag engine_frag threads_frag'
 
 # Initialize some variables set by options.
@@ -1045,6 +1045,8 @@ Optional Features:
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --enable-debug          Enable run-time debugging machinery [default=yes]
   --disable-debug         Disable assertion checking (but not -g)]
+  --enable-jvmpi          Enable JVMPI [default=no]
+  --disable-jvmpi         Disable JVMPI]
   --enable-xprofiling     Enable profiling for C and jitted code
   --enable-xdebugging     Enable debugging symbol generation for jitted code
   --enable-feedback       Enable generation of feedback data
@@ -4171,7 +4173,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4174 "configure"' > conftest.$ac_ext
+  echo '#line 4176 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5246,7 +5248,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5249:" \
+echo "$as_me:5251:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6257,11 +6259,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6260: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6262: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6264: \$? = $ac_status" >&5
+   echo "$as_me:6266: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6489,11 +6491,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6492: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6494: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6496: \$? = $ac_status" >&5
+   echo "$as_me:6498: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6556,11 +6558,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6559: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6561: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6563: \$? = $ac_status" >&5
+   echo "$as_me:6565: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8568,7 +8570,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8571 "configure"
+#line 8573 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8666,7 +8668,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8669 "configure"
+#line 8671 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10798,11 +10800,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10801: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10803: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10805: \$? = $ac_status" >&5
+   echo "$as_me:10807: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10865,11 +10867,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10868: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10870: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10872: \$? = $ac_status" >&5
+   echo "$as_me:10874: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12108,7 +12110,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12111 "configure"
+#line 12113 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12206,7 +12208,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12209 "configure"
+#line 12211 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13028,11 +13030,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13031: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13033: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13035: \$? = $ac_status" >&5
+   echo "$as_me:13037: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13095,11 +13097,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13098: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13100: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13102: \$? = $ac_status" >&5
+   echo "$as_me:13104: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15035,11 +15037,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15038: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15040: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15042: \$? = $ac_status" >&5
+   echo "$as_me:15044: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15267,11 +15269,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15270: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15272: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15274: \$? = $ac_status" >&5
+   echo "$as_me:15276: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15334,11 +15336,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15337: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15339: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15341: \$? = $ac_status" >&5
+   echo "$as_me:15343: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17346,7 +17348,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17349 "configure"
+#line 17351 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17444,7 +17446,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17447 "configure"
+#line 17449 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18766,6 +18768,7 @@ fi
 
 
 
+
 if test x"${want_engine}" != x""; then
 
   if test x"${want_engine}" = x"intrp"; then
@@ -18858,6 +18861,33 @@ case "$enable_debug" in
 no) CPPFLAGS="$CPPFLAGS -DNDEBUG";;
 *) CPPFLAGS="$CPPFLAGS -DKAFFE_VMDEBUG";;
 esac
+
+
+# Check whether --enable-debug or --disable-debug was given.
+if test "${enable_debug+set}" = set; then
+  enableval="$enable_debug"
+
+fi;
+case "$enable_jvmpi" in
+"") ;;
+no) ;;
+*)
+cat >>confdefs.h <<\_ACEOF
+#define ENABLE_JVMPI 1
+_ACEOF
+;;
+esac
+
+
+
+if test x"$enable_jvmpi" = x"yes"; then
+  ENABLE_JVMPI_TRUE=
+  ENABLE_JVMPI_FALSE='#'
+else
+  ENABLE_JVMPI_TRUE='#'
+  ENABLE_JVMPI_FALSE=
+fi
+
 
 
 
@@ -42286,6 +42316,8 @@ subdirs="$subdirs libltdl"
 
           ac_config_files="$ac_config_files libraries/Makefile"
 
+          ac_config_files="$ac_config_files kaffe/jvmpi/Makefile"
+
           ac_config_files="$ac_config_files kaffe/kaffevm/Makefile"
 
           ac_config_files="$ac_config_files kaffe/kaffevm/intrp/Makefile"
@@ -42550,6 +42582,13 @@ if test -z "${USE_JIT_TRUE}" && test -z "${USE_JIT_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"USE_JIT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"USE_JIT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_JVMPI_TRUE}" && test -z "${ENABLE_JVMPI_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_JVMPI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_JVMPI\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -43100,6 +43139,7 @@ do
   "replace/Makefile" ) CONFIG_FILES="$CONFIG_FILES replace/Makefile" ;;
   "kaffe/Makefile" ) CONFIG_FILES="$CONFIG_FILES kaffe/Makefile" ;;
   "libraries/Makefile" ) CONFIG_FILES="$CONFIG_FILES libraries/Makefile" ;;
+  "kaffe/jvmpi/Makefile" ) CONFIG_FILES="$CONFIG_FILES kaffe/jvmpi/Makefile" ;;
   "kaffe/kaffevm/Makefile" ) CONFIG_FILES="$CONFIG_FILES kaffe/kaffevm/Makefile" ;;
   "kaffe/kaffevm/intrp/Makefile" ) CONFIG_FILES="$CONFIG_FILES kaffe/kaffevm/intrp/Makefile" ;;
   "kaffe/kaffevm/jit/Makefile" ) CONFIG_FILES="$CONFIG_FILES kaffe/kaffevm/jit/Makefile" ;;
@@ -43337,6 +43377,8 @@ s,@HAVE_CONFIG_JIT_MD_H@,$HAVE_CONFIG_JIT_MD_H,;t t
 s,@USE_JIT_TRUE@,$USE_JIT_TRUE,;t t
 s,@USE_JIT_FALSE@,$USE_JIT_FALSE,;t t
 s,@ENGINE_NAME@,$ENGINE_NAME,;t t
+s,@ENABLE_JVMPI_TRUE@,$ENABLE_JVMPI_TRUE,;t t
+s,@ENABLE_JVMPI_FALSE@,$ENABLE_JVMPI_FALSE,;t t
 s,@DNSJAVA_JAR@,$DNSJAVA_JAR,;t t
 s,@HAVE_DNSJAVA_TRUE@,$HAVE_DNSJAVA_TRUE,;t t
 s,@HAVE_DNSJAVA_FALSE@,$HAVE_DNSJAVA_FALSE,;t t
