Gettext fixes + New JNI submodule + Patch for include/Makefile.in
	* configure.ac: Use AM_LCMESSAGES to check for LC_MESSAGES in
	locale.h. jni module added.

	* THIRDPARTY: Added a note concerning the kjc module in the CVS.

	* WHATSNEW: Updated some news message for kaffe-1.1.5 (or .6).

	* kaffe/kaffevm/jni.c,
	kaffe/kaffevm/jni_i.h,
	kaffe/kaffevm/jnirefs.h:
	Removed. Moved into their own directory.

	* kaffe/kaffevm/jni/jni.c,
	kaffe/kaffevm/jni/jni_i.h,
	kaffe/kaffevm/jni/jnirefs.h,
	kaffe/kaffevm/jni/Makefile.am,
	kaffe/kaffevm/jni/.cvsignore:
	New files.

	* kaffe/kaffe/main.c: Only call setlocale if
	HAVE_LCMESSAGES is set.

	* kaffe/kaffe/Makefile.am,
	kaffe/kaffeh/Makefile.am,
	kaffe/kaffevm/Makefile.am,
	kaffe/kaffevm/intrp/Makefile.am,
	kaffe/kaffevm/jit/Makefile.am,
	kaffe/kaffevm/jit3/Makefile.am,
	kaffe/kaffevm/systems/beos-native/Makefile.am,
	kaffe/kaffevm/systems/oskit-pthreads/Makefile.am,
	kaffe/kaffevm/systems/unix-jthreads/Makefile.am,
	kaffe/kaffevm/systems/unix-pthreads/Makefile.am,
	kaffe/kaffevm/verifier/Makefile.am,
	libraries/clib/awt/X/Makefile.am,
	libraries/clib/io/Makefile.am,
	libraries/clib/management/Makefile.am,
	libraries/clib/native/Makefile.am,
	libraries/clib/net/Makefile.am,
	libraries/clib/nio/Makefile.am,
	libraries/clib/security/Makefile.am:
	Include JNI subdirectory in the search path.

	* config/config.h.in,
	aclocal.m4,
	kaffe/kaffevm/Makefile.in,
	kaffe/kaffe/Makefile.in,
	kaffe/kaffeh/Makefile.in,
	kaffe/kaffevm/Makefile.in,
	kaffe/kaffevm/intrp/Makefile.in,
	kaffe/kaffevm/jit/Makefile.in,
	kaffe/kaffevm/jit3/Makefile.in,
	kaffe/kaffevm/systems/beos-native/Makefile.in,
	kaffe/kaffevm/systems/oskit-pthreads/Makefile.in,
	kaffe/kaffevm/systems/unix-jthreads/Makefile.in,
	kaffe/kaffevm/systems/unix-pthreads/Makefile.in,
	kaffe/kaffevm/verifier/Makefile.in,
	libraries/clib/awt/X/Makefile.in,
	libraries/clib/io/Makefile.in,
	libraries/clib/management/Makefile.in,
	libraries/clib/native/Makefile.in,
	libraries/clib/net/Makefile.in,
	libraries/clib/nio/Makefile.in,
	libraries/clib/security/Makefile.in,
	configure:
	Regenerated.

	* developers/patch-include-Makefile.diff:
	New workaround patch for automake include/Makefile.

	* developers/autogen.sh: Apply patch-include-Makefile.diff

	* include/Makefile.in: Removed an extra generated include from
	the distributed archive.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -25930,6 +25930,70 @@ _ACEOF
 
 
 
+  echo "$as_me:$LINENO: checking for LC_MESSAGES" >&5
+echo $ECHO_N "checking for LC_MESSAGES... $ECHO_C" >&6
+if test "${am_cv_val_LC_MESSAGES+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <locale.h>
+int
+main ()
+{
+return LC_MESSAGES
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  am_cv_val_LC_MESSAGES=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+am_cv_val_LC_MESSAGES=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $am_cv_val_LC_MESSAGES" >&5
+echo "${ECHO_T}$am_cv_val_LC_MESSAGES" >&6
+  if test $am_cv_val_LC_MESSAGES = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LC_MESSAGES 1
+_ACEOF
+
+  fi
+
+
+
 
 
 
@@ -54168,6 +54232,8 @@ subdirs="$subdirs libltdl"
 
           ac_config_files="$ac_config_files kaffe/kaffevm/verifier/Makefile"
 
+          ac_config_files="$ac_config_files kaffe/kaffevm/jni/Makefile"
+
           ac_config_files="$ac_config_files kaffe/kaffe/Makefile"
 
           ac_config_files="$ac_config_files kaffe/kaffeh/Makefile"
@@ -55043,6 +55109,7 @@ do
   "kaffe/kaffevm/systems/beos-native/Makefile" ) CONFIG_FILES="$CONFIG_FILES kaffe/kaffevm/systems/beos-native/Makefile" ;;
   "kaffe/kaffevm/systems/unix-pthreads/Makefile" ) CONFIG_FILES="$CONFIG_FILES kaffe/kaffevm/systems/unix-pthreads/Makefile" ;;
   "kaffe/kaffevm/verifier/Makefile" ) CONFIG_FILES="$CONFIG_FILES kaffe/kaffevm/verifier/Makefile" ;;
+  "kaffe/kaffevm/jni/Makefile" ) CONFIG_FILES="$CONFIG_FILES kaffe/kaffevm/jni/Makefile" ;;
   "kaffe/kaffe/Makefile" ) CONFIG_FILES="$CONFIG_FILES kaffe/kaffe/Makefile" ;;
   "kaffe/kaffeh/Makefile" ) CONFIG_FILES="$CONFIG_FILES kaffe/kaffeh/Makefile" ;;
   "kaffe/xprof/Makefile" ) CONFIG_FILES="$CONFIG_FILES kaffe/xprof/Makefile" ;;
