improved the configure error message when both jikes and ecj are selected
2006-07-15  Dalibor Topic  <robilad@kaffe.org>

        * configure.ac: Improved the error message when both
        jikes and ecj are selected in configure options.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -25519,8 +25519,8 @@ echo "${ECHO_T}$msg_use_jikes" >&6
 
 
 if test x"$use_ecj" = x"yes" -a x"$use_jikes" = x"yes"; then
-	{ { echo "$as_me:$LINENO: error: You must specify only one compiler" >&5
-echo "$as_me: error: You must specify only one compiler" >&2;}
+	{ { echo "$as_me:$LINENO: error: You can not chose jikes and ecj at the same time." >&5
+echo "$as_me: error: You can not chose jikes and ecj at the same time." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
